## CS 345 Exercise_01

This exercise provides a short reminder of key features of Numpy that are relevant to this course, including built in functions, linear algebra operations, random number generation and Boolean indexing. For every single cell, we will have the expected output shown below. Please take that as your reference.

Please change the file name to match this format before submitting your excercise for grading

    <last_name>_excercise_00.ipynb

In [3]:
import numpy as np
from numpy.random import default_rng

Given the Numpy array *my_array* and *my_list* below, demonstrate the speed advantage of Numpy arrays.


In [4]:
my_array = np.arange(1000000)
my_list = list(range(1000000))

In Cell 01, write code to square each number in the Numpy array and list, then use `%time` function to measure the execution time of your code. Noted that the running time will differ from a different machine, and your results of Cell 01 do not need to be exactly the same as the results shown below.

In [5]:
# Cell 01

print('Numpy Array:')
%time my_array2 = my_array * 2


print('Python List:')

# my_list[:100]
%time my_list2 = my_list * 2



Numpy Array:
CPU times: user 3.3 ms, sys: 2.1 ms, total: 5.4 ms
Wall time: 11.1 ms
Python List:
CPU times: user 12.8 ms, sys: 6 ms, total: 18.8 ms
Wall time: 18.5 ms


In Cell 02, write code to extract all the even numbers from the *array_1* below, put your results into a new array called *array_1_even* . Print your *array_1_even* out at the end.

In [6]:
# Cell 02
array_1 = np.arange(10)

array_1_even = np.array([i for i in array_1 if i % 2 == 0])

print('array_1_even:', array_1_even)

array_1_even: [0 2 4 6 8]


In Cell 03, write your code to create a new array called *array_1_copy* by duplicating the *array_1*, then replacing all the even numbers in *array_1_copy* by -1. Print your *array_1_copy* out at the end.

In [7]:
# Cell 03


array_1_copy = np.array([-1 if i % 2 == 0 else i for i in array_1])

print('array_1_copy:', array_1_copy)

array_1_copy: [-1  1 -1  3 -1  5 -1  7 -1  9]


In Cell 04, write your code to create a 4x4 array with random integers that range from (1, 100). Please set the seed of your random number generator as 42 and name your new array as *my_random_array*. Print your array out at the end. 

In [8]:
# Cell 04


rng = default_rng(77)
my_random_array = rng.integers(1,100, size=(4,4))


print('my_random_array: \n\n', my_random_array)

my_random_array: 

 [[ 6 78 63 55]
 [79 25 86 34]
 [96 32 36 39]
 [33 80 19  9]]


In Cell 05, given a 2X4 array *a* below, write your code to swap row1 and row2 in *a* without changing your original array *a*, create a new array *a_swap* to store your results. Print your *a_swap* out at the end.

In [17]:
# Cell 05
a = np.array([[5, 2, 8, 5, 5],
        [4, 2, 9, 8, 6]])
a_swap = np.array([np.array(a[1]), np.array(a[0])])

print('a_swap: \n\n', a_swap)

a_swap: 

 [[4 2 9 8 6]
 [5 2 8 5 5]]


In Cell 06, give the array *a* and *b* bellow, create a new array called *a_b* by stacking those two arrays horizontally. Print your *a_b* out at the end.

In [18]:
# Cell 06
a = np.array([[5, 2, 8, 5, 5],
        [4, 2, 9, 8, 6]])
b = np.array([[4, 8, 5, 4, 5],
        [3, 1, 5, 8, 1]])

a_b  = np.hstack([a,b])

print('a_b: \n\n', a_b)

a_b: 

 [[5 2 8 5 5 4 8 5 4 5]
 [4 2 9 8 6 3 1 5 8 1]]


In Cell 07, given arrays *a* and *b* below, write the code to set the items in array *a* to 0 if such item do not match the item in array *b* with the same positions. Noted that you don't need to create a new array here. Print the array *a* at the end.

In [20]:
# Cell 07
a = np.array([[5, 2, 8, 5, 5],
        [4, 2, 9, 8, 6]]) 
b = np.array([[4, 8, 5, 4, 5],
        [3, 1, 5, 8, 1]])


a[a != b] = 0

print('a: \n\n', a)

a: 

 [[0 0 0 0 5]
 [0 0 0 8 0]]


In Cell 08, given a 6x5 array *array_2* bellow, write your own code to compute the mean value of each row. Put your results into a new array called *array_2_mean*. Print your *array_2_mean* out at the end.


In [31]:
# Cell 08

array_2 = np.array([[17.53, 18.55, 18.18, 10.8 , 10.08],
       [ 6.64, 15.78, 14.51, 12.4 , 14.6 ],
       [14.67,  2.02, 10.34,  3.79,  6.73],
       [12.61,  5.4 , 19.07, 13.76, 15.39],
       [ 1.82,  7.79,  5.41, 20.  , 18.17],
       [10.01,  8.88, 17.27,  1.73, 13.64]])

array_2_mean = array_2.mean(axis = 1)

print('array_2_mean: \n\n',array_2_mean)

array_2_mean: 

 [15.028 12.786  7.51  13.246 10.638 10.306]


In Cell 09, round all the floats in your *array_2_mean* up to two decimals. Print your new *array_2_mean* out at the end. 

In [32]:
# Cell 09

array_2_mean = array_2_mean.round(decimals=2)

print('array_2_mean: \n\n',array_2_mean)

array_2_mean: 

 [15.03 12.79  7.51 13.25 10.64 10.31]


In cell 10, write the code to subtract the related raw mean from every item in your *array_2*, and create a new array called *array_2_subtraction* to store your results. Print your *array_2_subtraction* out at the end.

In [45]:
# Cell 10

array_2_subtraction =  array_2 - array_2_mean[:, np.newaxis]

print('array_2_subtraction: \n\n',array_2_subtraction)

array_2_subtraction: 

 [[ 2.5   3.52  3.15 -4.23 -4.95]
 [-6.15  2.99  1.72 -0.39  1.81]
 [ 7.16 -5.49  2.83 -3.72 -0.78]
 [-0.64 -7.85  5.82  0.51  2.14]
 [-8.82 -2.85 -5.23  9.36  7.53]
 [-0.3  -1.43  6.96 -8.58  3.33]]
